### PR TITLE
WIP: Spark / Elephas integration

### PR DESCRIPTION
**Pull request by zeynepakkalyoncu**
## Description
 Please include a summary of the change and which issue is fixed.
 
## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Todo
- [ ] Shrink model
- [ ] Implement distributed ensemble

### CODE REVIEW

**Comment by zeynepakkalyoncu** [comment]
Don't merge yet. Another commit with some minor fixes is coming soon.

**Comment by achyudhk** [comment]
Oh sure, I'll wait for further commits

**Comment by zeynepakkalyoncu** [comment]
Spark integration is still in progress, but other changes shouldn't break exiting functionality. Please review and merge.

**Comment by achyudhk** [comment]
The code changes look good to me. Was there any specific reason for including the dist/egg file?

**Comment by achyudhk** [comment]
I have resolved the merge conflicts. Feel free to merge whenever you are ready.

**Pull request merged**
